---
title: "2022 MEDS Public Presentations"
description: |
  The Master of Environmental Data Science (MEDS) cohort present their final results of the capstone group projects. This post links to my groups presentation directly, but all groups are in the same YouTube link.
author:
  - name: Cullen Molitor
    url: https://github.com/cullen-molitor
  - name: Juliet Cohen
    url: https://github.com/julietcohen
  - name: Steven Cognac
    url: https://github.com/cognack
  - name: Grace Lewin
    url: https://github.com/gracelewin
date: 2022-05-29
output:
  distill::distill_article:
    self_contained: false
preview: public_presentations.png
categories:
  - Python
  - Remote Sensing
  - Spatial Analysis
  - Africa
  - Agriculture
  - MOSAIKS
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### An open-source pipeline for remote sensing of crop yields: a Zambia case study

Our group capstone project has come to a close with our public presentation at Bren Hall, UCSB on May 26, 2022. More information on presenters and the schedule can be found [here](https://bren.ucsb.edu/events/2022-meds-capstone-project-presentations).

#### [**Presntation YouTube Link**](https://youtu.be/iXdETegKbSs?t=4372)

#### Abstract
High-quality, long-term environmental data sets are the foundation of long-range risk and climate modeling. However, producing such datasets is costly, logistically challenging, and resource-intensive. Due to limited agricultural data across sub-Saharan Africa, policy-makers, farmers, and researchers are currently unable to accurately forecast short-run food security risks posed by weather anomalies and long-run climate change projections. Recent machine learning approaches applied to high-resolution satellite imagery have successfully modeled various social and environmental variables. Here, we expand upon a recently developed machine learning approach to build a model that predicts maize yields over time using public satellite imagery. We developed a generalizable pipeline from survey data through a use case for predicting maize yields in Zambia. In 2020 and 2021, the Zambia Statistics Agency could not survey maize growers due to the COVID-19 pandemic. We use our model to fill in this data gap of maize yield predictions during these years. Through parameter optimization, we selected the model with the best ability to predict over space and time. Our model performed better overall relative to its predictive performance over time. The processed satellite imagery, predictions, and pipeline serve as a tool for the research community and users interested in analyzing Zambia’s current and future food security risks. This pipeline further enables users to explore global and region-specific questions at scale. 

#### Acknowledgemnts

Bren School: Tamma Carleton, Assistant Professor; Brad Hill, IT Director; Allison Horst, Assistant Teaching Professor; Kat Le, Technical Applications Manager

Jonathan Proctor, postdoctoral fellow at the Harvard Data Science Initiative and the Center for the Environment

Baylis Lab, University of California, Santa Barbara

Zambia Statistics Agency

Microsoft Planetary Computer: Caleb Robinson, Tom Augsburger


